[project]
name = "klima"
version = "0.1.0"
description = "A terminal based weather app without the bloat of modern web apps."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
    "textual>=6.11.0",
]
